### ISSUE TITLE
KNQX runways changed

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#101]
KNQX runways have changed:
- [x] Runway 7-25 is now Runway 8-26
- [x] Runway 3-21 is now Runway 4-22
- [x] Runway 13-31 is now Runway 14-32

**Comment by FriedrichKayak** [comment]
@erikquinn In the sector file, the static text labels are already updated. Is this about vSTARs or vERAM?

**Comment by erikquinn** [comment]
vSTARS doesn't use static text (big sad). If it's in the sector file already, then it's just a regeneration of the ASDE layer for vERAM.

**Comment by FriedrichKayak** [comment]
I don't understand why the map needs to be regenerated? Are static text labels embedded in the map in vERAM?

**Comment by erikquinn** [comment]
@FriedrichKayak yes, they are... but updating the sector file doesn't affect vERAM. And previously, we've been updating the sector file but not passing those changes through to vERAM, meaning you were up to date in VRC, but not in vERAM.
