### ISSUE TITLE
Add VRC color profiles

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#102]
People can't see shit when their video maps are bright green, just like the a/c. We should provide a set of color profiles that makes this less awful.

**Comment by FriedrichKayak** [comment]
We can make these available for import into VRC.

**Comment by FriedrichKayak** [comment]
If color profiles come along with session profiles, then we should merge this with #105 .

**Comment by FriedrichKayak** [comment]
Closed as duplicate of #105.
