### ISSUE TITLE
add a .monitor alias to monitor tower

### ISSUE THREAD

**Issue by reddishknight** [vZMA/ZMA#104]
- [x] `.mon` for `monitor (some callsign), (some frequency)`
- [x] `.nm` for `.nomarkers`
- [x] `.c` for `.center $1`
- [x] `.closedto` for `****NOTAM: $radioname() CLOSED at $time. All aircraft contact $radioname($1), $freq($1)****`
- [x] change `.GFLL` / `.GTPA` to `.VDFFLL` / `.VDFTPA`

**Comment by erikquinn** [comment]
Maybe as `.mon`, to match the existing `.con` for contact. Nice and easy 😄
