### ISSUE TITLE
Shrink ZMA 25?

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#12]
Currently, the entire WSC area is a single sector, 25. When the SSCOTs are heavy, it can be a lot, and isn't as easy to offload to others. If we could open a sector to the west that goes all the way down to Havana, it would help shrink the area the 25 controller has to look at, and gives them some help by having somebody else do some initial sequencing for the SSCOTs from Houston (which can also sometimes be busy). The new sector could also take TPA/RSW/EYW approaches as necessary to further alleviate the sectors working the arrivals into Miami.

Food for thought.,.

![image](https://user-images.githubusercontent.com/5103735/57904868-8cfbd600-7842-11e9-8bba-36d193df6b1f.png)

**Comment by FriedrichKayak** [comment]
@Shaneomac456  Please opine.

**Comment by erikquinn** [comment]
All figured out and implemented. Closing.
