### ISSUE TITLE
Add a coordinate fix to set a vispoint at kmia for vrc 3d mode. (Camperos request)

### ISSUE THREAD

**Issue by reddishknight** [vZMA/ZMA#122]
Add a coordinate fix to set a vispoint at kmia for vrc 3d mode. (Camperos request)

**Comment by erikquinn** [comment]
...for all airports!

**Comment by FriedrichKayak** [comment]
This will be migte's first change- however we will create a new issue for all other airports so that this doesn't get bogged down finding the tower at all fields.

**Comment by migte** [comment]
Tower Coordinates: `N25.47.36.854 W80.17.59.439`

**Comment by migte** [comment]
Per request, adding it for LAL, FPR, TMB, KAPF.

**Comment by migte** [comment]
Per request, adding it for LAL, FPR, TMB, KAPF.

**Comment by migte** [comment]
Woops, just read wat you said above about making new issues for other airports. Any future additions will be done through another issue.
