### ISSUE TITLE
investigate squawk assignment issues

### ISSUE THREAD

**Issue by FriedrichKayak** [vZMA/ZMA#127]
lately, we have experienced a large number of duplicate squawks for Miami departures- investigate root cause

**Comment by erikquinn** [comment]
In particular, this is observed with Nassau departures. Check _their_ POF and see if they are using our ranges. If so, let's come up with a proposed new set of squawk ranges to eliminate the overlap.

**Comment by FriedrichKayak** [comment]
Link for reference:
https://www.vatusa.net/docs/beacon_codes_for_vatusa.htm

**Comment by FriedrichKayak** [comment]
@erikquinn How has this been since Nassau adjusted their POF?

**Comment by erikquinn** [comment]
Cross-referencing our POF with theirs and ZJX's, I don't see any conflicts, so it should all be good. Closing.
