### ISSUE TITLE
Change color of gate labels on MIA ASDE when that gate pushes onto a taxiway

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#13]

**Comment by FriedrichKayak** [comment]
Is there a definitive list of these gates?

**Comment by erikquinn** [comment]
Being generated in the tower sop update. Will be VERY easy to regenerate the gate labels so you can apply color to the right group of gates.

**Comment by FriedrichKayak** [comment]
I see there's a list in the current SOP. Will you be regenerating all the elements you recently sent with the color change, or only the ones with a color change?

**Comment by erikquinn** [comment]
Whichever you need

**Comment by FriedrichKayak** [comment]
@erikquinn Please regenerate the entirety of what you sent previously so I can delete the entire block and replace it.
