### ISSUE TITLE
Rename PDR aliases by airport, not by VDF

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#135]
PDR aliases should be usable without specifying the departure fix, and just the airport. i.e. instead of `.HEDLYQ87`, you could do `.MIAQ87 / .MQ87` or `.FLLQ87 / .FQ87`. When they file the wrong departure fix, it's easier to find the right routing if you don't have to remember which fix should be used to get there.

**Comment by migte** [comment]
On the Alias PR, I also applied this to the PDC PDAR aliases. Not sure if that was the intention of this issue or not but if it was yay if it wasn't feel free to let me know and I'll change it back.
