### ISSUE TITLE
Add autotrack group aliases

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#143]
Add airports to autotrack list based on approach control(s).

**Comment by FriedrichKayak** [comment]
I presume this is primarily for benefit of vERAM users? Otherwise, vSTARs users would just `.autotrack ALL`?

**Comment by erikquinn** [comment]
I had no idea you could `.autotrack all` honestly, but yes, of great importance to vERAM users. It takes too much effort to do them all individually `.autotrack kmia kfll ktpa ksrq kpbi keyw`, or changes when approach controls sign on/off, etc.

**Comment by erikquinn** [comment]
.AT .AUTOTRACK
.ATM .AUTOTRACK KMIA KFLL KHST KTMB KOPF KHWO KFXE KPMP
	.XATM .AUTOTRACK -KMIA -KFLL -KHST -KTMB -KOPF -KHWO -KFXE -KPMP
.ATT .AUTOTRACK KTPA KSRQ KSPG KMCF KPIE KLAL KBOW KBKV
	.XATT .AUTOTRACK -KTPA -KSRQ -KSPG -KMCF -KPIE -KLAL -KBOW -KBKV
.ATP .AUTOTRACK KPBI KVRB KFPR KSUA 06FA KBCT
	.XATP .AUTOTRACK -KPBI -KVRB -KFPR -KSUA -06FA -KBCT
.ATR .AUTOTRACK KRSW KFMY KPGD KAPF
	.XATR .AUTOTRACK -KRSW -KFMY -KPGD -KAPF
.ATE .AUTOTRACK KEYW KNQX
	.XATE .AUTOTRACK -KEYW -KNQX

.ATALL .AUTOTRACK KMIA KFLL KHST KTMB KOPF KHWO KFXE KPMP KTPA KSRQ KSPG KMCF KPIE KLAL KBOW KBKV KPBI KVRB KFPR KSUA 06FA KBCT KRSW KFMY KPGD KAPF KEYW KNQX
	.XATALL .AUTOTRACK NONE

**Comment by Shaneomac456** [comment]
Added
