### ISSUE TITLE
Make Nassau "orange area" a separate diagram

### ISSUE THREAD

**Issue by FriedrichKayak** [vZMA/ZMA#15]
Make the Nassau "orange area" from the latest LOA a separate diagram in the sector file so that it can be toggled independently. Requests by @reddishknight.

**Comment by erikquinn** [comment]
Don't like it as bring part of the regular map? :Confused:

**Comment by reddishknight** [comment]
If I want to see the boundary for say working 40/41 I don’t want to get hit by every sector.

**Comment by erikquinn** [comment]
.......wat?

**Comment by FriedrichKayak** [comment]
Can we have a joint requirements meeting about this one at the next opportunity?
