### ISSUE TITLE
FLL PDCs have 3000 instead of 4000

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#157]
Update FLL PDCs (such as `.pdcfaf` etc) to show the new initial altitude of 4k instead of the old 3k.

**Comment by ksnifte** [comment]
I'm baaaaaaack 🎉

Anyway... question for @erikquinn -- it looks like KRSW has an SOP update where N Deps are 4000 and S Deps are 3000.  Do we need to reflect that in the Alias file?  (such as `.pdcrafn` `.pdcrafs` or something like that)
