### ISSUE TITLE
CURSO5 arrival, investigate use of FRRDY EPENY VICLB and IBISS

### ISSUE THREAD

**Issue by FriedrichKayak** [vZMA/ZMA#19]
May need some new fixes based on current arrival, but the current version may suffice. Specifically, missing BEETR.

			  JODPO JODPO FRRDY FRRDY
                          JODPO JODPO EPENY EPENY
                          JODPO JODPO GRITT GRITT
                          JODPO JODPO LECIT LECIT
			  LECIT LECIT VICLB VICLB
                          LECIT LECIT IBISS IBISS

**Comment by gerardojro** [comment]
This issue should be closed as CURSO is no longer in use.
