### ISSUE TITLE
New Twy and Hangar at KLAL

### ISSUE THREAD

**Issue by ksnifte** [vZMA/ZMA#34]
There has been construction in the NW corner of KLAL and they've added Twy M to go to whatever they're building up there.

Also, a new hangar has been added at H.

Both are visible on Jeppesen and FAA charts:
![image](https://user-images.githubusercontent.com/59857918/72318493-0a8e1500-3662-11ea-87df-bc0e249a730c.png)

**Comment by ksnifte** [comment]
**MERGE CONFLICT WARNING:**
It would be advisable to merge PR #35 before working this.  There is one modification to Twy H that would cause conflicts between the branches.

**Comment by FriedrichKayak** [comment]
They are building the new Amazon hub. Major improvements to 9-27 are underway. After Sun N Fun this year, 9-27 will be renamed 10-28, which will someday become 10L-28R, when they build a parallel and turn 5-23 into a taxiway.
