### ISSUE TITLE
Add 3000/4500/6000 + ADW markings to ASDEs

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#39]
For SRS application, it'd be nice to have little markings showing SRS and ADW markings with tiny labels.

**Comment by ksnifte** [comment]
This ticket is next on my to-do list.  @erikquinn and @FriedrichKayak, which airports do we want the SRS markings for?

**Comment by erikquinn** [comment]
All towered fields, I would say... but maybe start with just like KMIA so we can make changes to the appearance before going and doing the rest of them.

**Comment by ksnifte** [comment]
Sounds good to me, wilco

**Comment by ksnifte** [comment]
Unless there are objections, here's how I'm planning on speccing this out:

Rough design:  https://prnt.sc/qxppgc

Shane said we don't have any Class Ds that aren't in a tracon, so each tracon will get its own set of "Runway Reference Diagrams".  Each set of RRDs will contain a "Primary Flow" diagram and a "Secondary Flow" diagram.  The Primary Flow diagram will show SRS and ADW markings for the Calm Wind Config at each airport, and the Secondary Flow will show the opposite direction.  In the case that an airport doesn't have a Calm Wind Config outlined by SOP, East/North will be considered "primary" for the sake of the diagrams.

Unless someone opposes this, I intend to list these diagrams after the "AIRPORT DIAGRAMS" section of the VRC diagrams.

**Comment by erikquinn** [comment]
I would think they'd go directly in the ASDE maps, and be much more subtle so it's not a bother having them on all the time.

**Comment by FriedrichKayak** [comment]
> I would think they'd go directly in the ASDE maps, and be much more subtle so it's not a bother having them on all the time.

@erikquinn Wouldn't that mean we have two sets of markings for opposite direction use on the same diagram? For me, that would add clutter and confusion. I propose that we stick with @ksnifte original plan for the time being, then make them toggle-able separate diagrams during a trial period (production-use trial) during which we can plan how they will be ultimately integrated. This will make speed to market faster and also simplify a back out if we need to remove them (since they will all be in one code block).

**Comment by FriedrichKayak** [comment]
@ksnifte Any proposal on rendering the ADWs?

**Comment by ksnifte** [comment]
> .... For me, that would add clutter and confusion. ... **This will make speed to market faster and also simplify a back out if we need to remove them (since they will all be in one code block).** ....

I agree with your comments on all counts.


> Any proposal on rendering the ADWs?

@FriedrichKayak, @erikquinn and I had a brief conversation about this this morning and my current intent is to mark them on their own per-airport diagram.  I'll be putting together a couple mockups in the next couple days for folks to look over and decide how we want them to look, unless there's already an existing vision in mind.

**Comment by ksnifte** [comment]
Proposed mockup: https://prnt.sc/qzmylk

The blue is the VMC ADWs and the purple is the IMC ADWs.  They will be in two separate diagrams that are selectable individually based on weather conditions.

I will begin development on Wednesday (2/12) if there is no opposition to any of the discussed plans by then.

**Comment by erikquinn** [comment]
Are the inners marked in your diagram?
