### ISSUE TITLE
Update KFLL Diagram(s)

### ISSUE THREAD

**Issue by ksnifte** [vZMA/ZMA#42]
Updates have happened, including a reconfiguration at 10L
https://aeronav.faa.gov/d-tpp/2001/00744AD.PDF.

Also, the tracon video maps need to be updated to reflect the removal of Rwy 14/32 and extension of 10R/28L

**Comment by ksnifte** [comment]
Closing this at stale since it was mostly resolved with Nicholas' new ASDE updates at MIA & FLL.  Creating a fresh ticket for some things that need to be done at KFLL for vSTARS.

**Comment by erikquinn** [comment]
The latest Miami vSTARS should have that already resolved as well; it's very new. Post metroplex.
