### ISSUE TITLE
Size of Palm Beach TRACON is bigger than sector file denotes

### ISSUE THREAD

**Issue by FriedrichKayak** [vZMA/ZMA#5]

**Comment by erikquinn** [comment]
The SOPs need an update to this effect, once we get through to fully establishing what the airspace will be. It's not actually a flat-top like we currently treat it.

**Comment by FriedrichKayak** [comment]
Are we referring to the green boundary here that surrounds PBI, that appears as part of the High Boundaries toggle in VRC?

https://i.gyazo.com/cd1b8a483c13f010e598e6387b71f331.png

**Comment by erikquinn** [comment]
Right, there's an area about that large to the north of what's shown in green where PBI TRACON now works what used to be ZMA sector 3, providing approach services to VRB, FPR, etc. I can't find a reference for this at the moment though...

**Comment by FriedrichKayak** [comment]
The map for this (ST-N and ST-S) airspace can be found on pages 85-88 of the PBI SOP.

**Comment by erikquinn** [comment]
It was in the vERAM file. We now have an updated APCH BDRY map which can also be used in VRC.
The area between regular PBI and F11 belongs to PBIz 5000 and below (generally), with two small triangles at the NW and NE corners which are 4000 and below (presumably for ZMA to hand off MLB arrivals to F11 without touching PBIz).

**Comment by erikquinn** [comment]
This has already been added to the version on master. Closing.
