### ISSUE TITLE
Add "are you able to accept the following route" alias

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#55]
another controller requested

**Comment by FriedrichKayak** [comment]
Since there cannot be spaces in the argument, so we'd need to change the flight plan before issuing this command. This could lead to confusion if the original route is needed. This will be planned for the  2007 release.

**Comment by erikquinn** [comment]
You can allow it to bleed over, just don't use punctuation at the end. For example, define as `.ablenewroute Please advise if you are able to accept the following route: $1`

Then, using `.ablenewroute GANDY8 SABEE BAARY SSCOT5` would yield `Please advise if you are able to accept the following route: GANDY8 SABEE BAARY SSCOT5`

It only took GANDY8 as the argument, but everything beyond is just appended to the end, so from the user's end, it works perfectly.

**Comment by FriedrichKayak** [comment]
.ABLERTE and .ABLEDEP added

**Comment by erikquinn** [comment]
@FriedrichKayak Where are these changes? I don't see them on the `docs/alias/alias.txt` on the master branch. Can add them to #66 if you want?
