### ISSUE TITLE
vERAM Radar coverage

### ISSUE THREAD

**Issue by Shaneomac456** [vZMA/ZMA#62]
Increase the BHF radar station SSR range to 250 to include radar coverage of CAPRX on AR3.

**Comment by FriedrichKayak** [comment]
Have you already tested that 250 is the correct range to include CAPRX? It's easy enough to make the change, but I just want to be sure I don't need to test the behavior to assure coverage.

**Comment by Shaneomac456** [comment]
Yes, hence I gave you an exact number to change it to. :P
