### ISSUE TITLE
Update KTPA TwrTrainer Apt File

### ISSUE THREAD

**Issue by ksnifte** [vZMA/ZMA#64]
Lots of changes at KTPA have left the TwrTrainer file quite outdated.  Needs to be brought up to current.  Mostly needs taxiways fixed.

**Comment by FriedrichKayak** [comment]
Propose closing this ticket since Erik indicated TwrTrainer files are education department domain.

**Comment by ksnifte** [comment]
@FriedrichKayak Works for me.  Erik and I chatted while you were talking to your friends at the Bell and I'm going to go ahead and still update the file for him-- but I see no real reason for this ticket to stay up since it's out of our department now.
