### ISSUE TITLE
fix .tr .trhs .trcr .trf aliases so they don't handle multi-taxiway routes wonky

### ISSUE THREAD

**Issue by FriedrichKayak** [vZMA/ZMA#69]
currently, .tr 8R N N14 M yields  "Runway 8R, taxi via N. N14 M" due to the period at the end. Others need evaluation.

**Comment by erikquinn** [comment]
Highly recommend separating by hyphens instead, to allow this to work normally and also support stuff where instructions exist after the taxi route (like runway 1 taxi via A-B-C, hold short of D... ".trhs 1 a-b-c d"

I've been using this technique and once adjusted to it, I've found it to be quite a fine solution.

**Comment by ksnifte** [comment]
> 
> 
> Highly recommend separating by hyphens instead, to allow this to work normally and also support stuff where instructions exist after the taxi route (like runway 1 taxi via A-B-C, hold short of D... ".trhs 1 a-b-c d"
> 
> I've been using this technique and once adjusted to it, I've found it to be quite a fine solution.

I hadn't considered this, but now that it's been mentioned, I agree with this.  Also, doing what Erik has said maintains the integrity of the the `$uc` casting.... otherwise, even without the built-in period, you get this: `.tr 8R a b c  --> Runway 8R, taxi via A b c`.

With the built-in period, you get this:
```
.trhs 8R a-b-c-c2 d Give way to the American 73 from the right at V
==> Runway 8R, taxi via A-B-C-C2, hold short of D.  Give way to the American 73 from the right at V
```

**Comment by erikquinn** [comment]
Yep, being able to still have the period so you can custom-type another sentence is clutch sometimes!

**Comment by FriedrichKayak** [comment]
I was also doing this, when I noticed the behavior. However, I was worried that folks wouldn't catch onto this. As long as @erikquinn  is happy to undertake a change to the official curricula to reinforce this training imperative, we can approve this and refer to it as "The 2020 Hyphen Accord." @ksnifte Can you have a look at the alias file and identify and make these consistent?

**Comment by ksnifte** [comment]
@FriedrichKayak Will do-- I'll also update the Alias Ref doc to reflect the intended hyphenated use.

**Comment by erikquinn** [comment]
Sure, I can blast out an email about it. Word will spread like wildfire about the strategy I'm sure.
