### ISSUE TITLE
KMIA - add ramp lines, gates, and spots

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#8]
Add taxilane lines in the nonmovement area, and label gates and ramp spots to help ground controllers better visualize the absence or presence of conflicts between aircraft transiting the nonmovement areas.

**Comment by erikquinn** [comment]
Maps are complete, and available here:

[newmaps.txt](https://github.com/vZMA/ZMA/files/3242426/newmaps.txt)


- [ ] The entire section labeled `|--CENTER SECTORS--|` should be removed, as these sectors are old, and replaced by the new maps provided.
- [ ] The entire section labeled `|--ZJX--|` should be removed, as it is also out of date, and replaced by the new maps provided (the same information can be seen from the "ZMA HANDOFF" map)
- [ ] Under the `|--NASSAU--|` section, the `Nassau FIR` map should be removed. It's coordinates are wrong, and the correct ones are built into the `ZMA BOUNDARIES` map.

**Comment by FriedrichKayak** [comment]
All issues resolved and committed, to be included in 1906.
