### ISSUE TITLE
Fix some intersections

### ISSUE THREAD

**Issue by erikquinn** [vZMA/ZMA#98]
- [ ] TANIA is listed twice somehow
- [ ] MGNTY is missing on Q65/Q81
- [ ] DEANR is missing on Q109/Q116
- [ ] QUODS is missing on Y259
- [ ] FONDS is missing on Y217
- [ ] CANVI appears to have moved

![image](https://user-images.githubusercontent.com/5103735/93691313-79552500-fab1-11ea-9e9d-a66dd8bb9e82.png)

**Comment by FriedrichKayak** [comment]
turns out, this was an error with myfsim. read in the data from FAA and fixed it all.
